// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_local_variable

library schema;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


class SignupForm {
  SignupForm._(this._bc, this._bcOffset);
  factory SignupForm(List<int> bytes) {
    fb.BufferContext rootRef = new fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SignupForm> reader = const _SignupFormReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String get email => const fb.StringReader().vTableGet(_bc, _bcOffset, 4, null);
  String get password => const fb.StringReader().vTableGet(_bc, _bcOffset, 6, null);
  int get id => const fb.Int16Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'SignupForm{email: $email, password: $password, id: $id}';
  }
}

class _SignupFormReader extends fb.TableReader<SignupForm> {
  const _SignupFormReader();

  @override
  SignupForm createObject(fb.BufferContext bc, int offset) => 
    new SignupForm._(bc, offset);
}

class SignupFormBuilder {
  SignupFormBuilder(this.fbBuilder) {
    assert(fbBuilder != null);
  }

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable();
  }

  int addEmailOffset(int offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addPasswordOffset(int offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addId(int id) {
    fbBuilder.addInt16(2, id);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SignupFormObjectBuilder extends fb.ObjectBuilder {
  final String _email;
  final String _password;
  final int _id;

  SignupFormObjectBuilder({
    String email,
    String password,
    int id,
  })
      : _email = email,
        _password = password,
        _id = id;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(
    fb.Builder fbBuilder) {
    assert(fbBuilder != null);
    final int emailOffset = fbBuilder.writeString(_email);
    final int passwordOffset = fbBuilder.writeString(_password);

    fbBuilder.startTable();
    if (emailOffset != null) {
      fbBuilder.addOffset(0, emailOffset);
    }
    if (passwordOffset != null) {
      fbBuilder.addOffset(1, passwordOffset);
    }
    fbBuilder.addInt16(2, _id);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String fileIdentifier]) {
    fb.Builder fbBuilder = new fb.Builder();
    int offset = finish(fbBuilder);
    return fbBuilder.finish(offset, fileIdentifier);
  }
}
